### ISSUE TITLE
Search dosen't work properly

### ISSUE THREAD

**Issue by HekmatBeigverdi** [savanihd/Laravel-5-Angularjs-CRUD-with-Search-and-Pagination#1]
When clear all of text in search box ,sometimes dosen't show all of data

Thanks!

**Comment by savanihd** [comment]
go on public/app/controllers/ItemController.js and change $scope.searchDB function:
$scope.searchDB = function(){
      if($scope.searchText.length >= 3){
          if($.isEmptyObject($scope.libraryTemp)){
              $scope.libraryTemp = $scope.data;
              $scope.totalItemsTemp = $scope.totalItems;
              $scope.data = {};
          }
          getResultsPage(1);
      }else{
          if(! $.isEmptyObject($scope.libraryTemp)){
              $scope.data = $scope.libraryTemp ;
              $scope.totalItems = $scope.totalItemsTemp;
              $scope.libraryTemp = {};
          }
      }
  }

INTO

$scope.searchDB = function(){
    if($.isEmptyObject($scope.libraryTemp)){
        $scope.libraryTemp = $scope.data;
        $scope.totalItemsTemp = $scope.totalItems;
        $scope.data = {};
    }
    getResultsPage(1);
  }

I did search after 3 char. but you can change
